### PR TITLE
Gravity Simulation Game

### PR DESCRIPTION
**Pull request by Khushi-Pushkar**
# Description
Observe and Differentiate between the gravitational fields of Sun, Mercury, Venus, Earth, Moon, Mars, Jupiter, Saturn, Uranus, Neptune and Pluto.

Fixes:  #2137 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-07-13 062222

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by sanjay-kv** [comment]
image

@Khushi-Pushkar I will be reducing the extra points as per the guidelines. There is only 150 points awarded on this repo.
If any appeal please comment below.

image

Same goes for the codeharbour

**Comment by Khushi-Pushkar** [comment]
> image
> 
> @Khushi-Pushkar I will be reducing the extra points as per the guidelines. There is only 150 points awarded on this repo.
> If any appeal please comment below.
> 
> image
> 
> Same goes for the codeharbour

Sure, here's the improved version:

---

Sir, I was aware that this repositories had a 200-point limit previously. Due to the new guidelines setting the limit at 150 points, I humbly request that you reconsider and allow the limit to remain at 200 points. Thank you for your understanding.

**Comment by sanjay-kv** [comment]
sure. 200 points will be given as I can see you have not contributed after june

**Comment by Khushi-Pushkar** [comment]
> sure. 200 points will be given as I can see you have not contributed after june



> sure. 200 points will be given as I can see you have not contributed after june

I have noticed a discrepancy in my points calculation. According to my understanding, my points should be 930 in the leaderboard, but it currently shows 915. 
- Initially, I had 1055 points.
- 170 points were deducted, which should have resulted in 885 points.
- After resolving a level 3 issue, 45 points were added, making it 930 points.
Could you please look into this matter and make the necessary adjustments?

Thank you for your attention to this issue.

**Pull request merged**
