### PR TITLE
New: Hit Bugs with Sound Effects, Music and add timer !

### PR DESCRIPTION
**Pull request by ankit071105**
# Problem Description :-  [#2349]
We can enhance to the Bug Eliminator game with sound effects, background music, a timer, and an end-screen that shows the score and allows players to play again.

# Solution :-
Background Music:
Add background music that plays continuously while the game is active.
Sound Effect for Mosquito Hit:
Add a sound effect that plays whenever a mosquito is hit.
30-Second Timer:
Implement a timer that counts down from 30 seconds.
When the timer reaches zero, display the player's score and a "Play Again" button.

#Solution-Video :-

https://github.com/user-attachments/assets/0fb6b1e6-47ca-4c96-9dc0-259afc284044

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this as per the above conversation

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Why did you added the PR which is already added @ankit071105 

Kindly respond Immediately

**Comment by Sulagna-Dutta-Roy** [comment]
Bug elimiitator is already exists I mentioned. If you want to enhance any project then you should have opened new Issue mentioning 'Enhancing the UI': Bug Eliminator @ankit071105 

Respond please

**Comment by ankit071105** [comment]
For sure I will look into the new issue @Sulagna-Dutta-Roy . You have assigned that so I have created a PR .

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check again #2143 Is that the Issue? I have assigned? @ankit071105

**Comment by ankit071105** [comment]
No you have assigned me an issue i have pasted the wrong one by mistake . @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Yeah. Kindly cross check before the pull request. Thank you @ankit071105

**Comment by ankit071105** [comment]
Okay can you accept my PR ?

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Currently duplicate projects not accepting here strictly @ankit071105 
Bug eliminator was added before I mentioned already in the #2349. Still you have created the PR. Reducing the level to 1 

I will not accept onwards if any duplicate one raised, will close the issue immediately

**Comment by ankit071105** [comment]
Thanks for the concern and I will be looking forward to contributing to the real time projects

**Pull request merged**
