### PR TITLE
Add game Call Of Duty

### PR DESCRIPTION
**Pull request by arunimaChintu**
# Description

Adds game Call Of Duty
Fixes:  #1941 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Changing the levels and change the directory name: Call of Duty/your files

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy I have updated the directory name. Please merge this

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly check and raise the PRs like this: #1986 
Added the pull request no for your reference. I hope it will be helpful @arunimaChintu

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this one as I received new PR @arunimaChintu

**Pull request closed without merging**
