### PR TITLE
Added World Capital

### PR DESCRIPTION
**Pull request by akshbansal61203**
The World Capital Quiz is an interactive and educational browser extension designed to enhance your knowledge of world capitals. This extension seamlessly integrates into your browser, providing a convenient and engaging way to learn and test your geography skills.

Key Features:

Educational Focus: The extension contains a comprehensive collection of quizzes on world capitals. It covers capitals from all continents, helping you learn and memorize the capitals of countries worldwide.

Knowledge Reinforcement: By regularly engaging with the World Capital Quiz, users can reinforce their geographical knowledge, ensuring a solid understanding of world capitals. The quizzes are designed to challenge your memory and improve your retention of geographical information.

Self-Confidence Booster: The incremental difficulty of the quizzes helps build self-confidence. As you progress and successfully answer more challenging questions, you gain a sense of achievement and readiness for geography competitions or trivia games.

Fixes:  #1472 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/123982568/28e8d619-dcc7-4859-8061-4e7e954a3be0

### CODE REVIEW

**Comment by akshbansal61203** [comment]
@Sulagna-Dutta-Roy Please assign me a higher level label, given the task's complexity and individuality.
Thank You.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly check the directory name

**Comment by akshbansal61203** [comment]
I have changed the directory name pls check.

**Comment by akshbansal61203** [comment]
Please provide me a higher label as well if suitable. Thank you

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
