### PR TITLE
Added boXmerge Game

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#2531

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #2531 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/user-attachments/assets/fe7268b5-0101-40bd-9162-2ef8d05b3474

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
KIndly delete all the package files and also mention the tech stack when opening an Issue. because my accepting JS now not reactJs. @Anjaliavv51 
Change the directory name: Box Merge Game/your files

**Comment by Anjaliavv51** [comment]
> @Sulagna-Dutta-Roy I will rewrite the code in JS

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy It is done game is modified to HTML CSS JS code.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy It is done game is modified to HTML CSS JS code.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy It is done game is modified to HTML CSS JS code.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
