### PR TITLE
Bug Eliminator game extension added

### PR DESCRIPTION
**Pull request by chaanakyaaM**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I have added the bug eliminator game extension

Fixes:  #2106 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Wanted to understand why did you make a Pull request for this? This is the same project exists on my repository and I mentioned yesterday in the issue's comment section.
@chaanakyaaM Kindly respond urgently

**Comment by Sulagna-Dutta-Roy** [comment]
https://github.com/Sulagna-Dutta-Roy/GGExtensions/issues/2349#issuecomment-2226315645 

Wanted to know your views on this? @chaanakyaaM 
Please respond

**Comment by chaanakyaaM** [comment]
My sincere apologies to you @Sulagna-Dutta-Roy , I have copied the code from the internet.

**Comment by Sulagna-Dutta-Roy** [comment]
So there's a rule in Gssoc. Contributors do copy from chatgpt. So I can't accept the fact that the issue already exists and I closed it earlier (Mentioned already) 

So cancelling this PR @chaanakyaaM

**Comment by Sulagna-Dutta-Roy** [comment]
Did you cheated on all the projects that you've done till now on my repo? @chaanakyaaM

**Comment by chaanakyaaM** [comment]
No

**Comment by Sulagna-Dutta-Roy** [comment]
No problem. @chaanakyaaM

**Comment by Sulagna-Dutta-Roy** [comment]
Sincerely apologies, I had to respond to this in another comment section. Because no mentors available here I had responded here @chaanakyaaM 

Apologies again. And do not copy anything from the chatgpt. Make your own project if possible

**Comment by chaanakyaaM** [comment]
Thank you so much.

**Pull request merged**
