### PR TITLE
Live Cricket Extension

### PR DESCRIPTION
**Pull request by harshnayangithub**
# Description

This PR adds a new extension in this codebase repository as the Cricket Live, as requested in issue #22 . It implements the ability to fetch and display ongoing and upcoming matches along with scores from the Cricket Data API in the extension popup.

Fixes:  #22 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by prasad-chavan1** [comment]
@harshnayangithub Make sure that you are commenting on important parts or sections of code its a good practice and you can rename folder as Live Cricket Extension/ allFiles

**Comment by harshnayangithub** [comment]
@prasad-chavan1 thanks for your suggestion, I will keep all those points in mind from now on.

**Comment by prasad-chavan1** [comment]
> @prasad-chavan1 thanks for your suggestion, I will keep all those points in mind from now on.

Now instead of adding files via upload why you aren't learning pulling changes pushing changes from your vsCode terminal ? Again im saying follow good practices watch tutorials or just read README.md of our repository and follow those commands set & finally try to adding comments in code its very good practice :)

**Comment by harshnayangithub** [comment]
Already knows it but for some images, I just uploaded it from my local machine.
image
image

**Comment by prasad-chavan1** [comment]
> Already knows it but for some images, I just uploaded it from my local machine. image image

Yoooo

**Comment by harshnayangithub** [comment]
@prasad-chavan1 done with all the changes you told me

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
