### PR TITLE
Click the button

### PR DESCRIPTION
**Pull request by taneeshaa15**
Hi @Sulagna-Dutta-Roy ,
I hope you're doing well. I've addressed the issue #1435 and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please review it.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Wanted to understand why did you add your project in the another folder. I see that you have added your project in Hexadecimal Calculator @taneeshaa15

**Comment by taneeshaa15** [comment]
Mam by mistake, i did that
correcting my mistake now.

**Comment by taneeshaa15** [comment]
Please review it again.
Thanks

**Comment by Sulagna-Dutta-Roy** [comment]
> Please review it again. Thanks

It still same

**Pull request closed without merging**
