### PR TITLE
Added bmi calculator

### LINKED ISSUE #324: BMI Calculator
Could you plz assign me this issue under gssoc 24

**Is your feature request related to a problem? Please describe.**

Calculating BMI can be time-consuming and prone to errors, especially for those who are not familiar with the formula or what the BMI ranges mean. Additionally, there's a lack of a user-friendly, accessible tool that can quickly provide accurate BMI calculations along with health recommendations based on the results.

**Describe the solution you'd like**

I would like an easy-to-use BMI calculator feature that:

Allows users to input their height and weight.
Instantly calculates their BMI.
Provides immediate feedback on which BMI category they fall into (e.g., underweight, normal weight, overweight, obese).

**Describe alternatives you've considered**

Using existing online BMI calculators, but many are cluttered with ads and not user-friendly

**Additional context**

bmi

What problem is this feature trying to solve?

How do we know when the feature is complete?

### PR DESCRIPTION
**Pull request by harshmishra19**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

The BMI (Body Mass Index) Calculator extension is a web-based tool that allows users to quickly and easily calculate their BMI.
Features:
User Input: Users can enter their weight and height into input fields provided on the web page.
Calculation: Upon clicking the "Calculate BMI" button, the extension computes the BMI based on the formula:

This PR fixes #324 

Fixes:  #324 

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x] I have made this from my own
- [ x] I have taken help from some online resources 
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/115486960/a9231766-3638-423a-aba5-03c57e69784f

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Check the branch because I can see folders for focus extension. 
Also change the directory name: BMI Calculator/your files.

**Comment by harshmishra19** [comment]
@Sulagna-Dutta-Roy While integrating the BMI calculator, I encountered some duplicate file errors in the Focus extension. To resolve these issues, I renamed certain files, which is why you may notice edits in the Focus extension. Additionally, I have renamed the extension to "BMI Calculator" and included the issue number along with relevant details in the pull request (PR) template

**Comment by Sulagna-Dutta-Roy** [comment]
Please work one at a time. Because otherwise it will show multiple changes. Which might be confusing.

**Comment by harshmishra19** [comment]
Now its not showing any error everything is working fine

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
No, actually if you want to add more changes other than a specific PR then kindly raise issues. Then make a another PR.

**Pull request merged**
