### PR TITLE
[New Game]:want to Add New Game Dante !! #2474

### PR DESCRIPTION
**Pull request by nishant0708**
# Description

Added New Game Dante

Fixes:  #2474

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X ] I have made this from my own
- [ X] I have taken help from some online resourses 
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add manifest files @nishant0708

**Comment by nishant0708** [comment]
@Sulagna-Dutta-Roy  Added Mam

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
package.json and manifest.json is totally different. You have added react package, kindly check again @nishant0708

**Comment by nishant0708** [comment]
please check now mam i guess it should work now

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly delete the package.json it's not needed @nishant0708

**Comment by nishant0708** [comment]
Done mam @Sulagna-Dutta-Roy

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
