### PR TITLE
LeetHub created

### PR DESCRIPTION
**Pull request by Aksshay88**
# Description

I have included the Leethub GC Extension where I have added the working code of the GC Extension of LeetHub that is used to store the code of the Leetcode solved problems in the github 

Even We could store the GFG solved problem in the github 

Fixes:  #727

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image

### CODE REVIEW

**Comment by Aksshay88** [comment]
Pls do add the GSSOC Label So that My contribution will be evaluated

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly delete all the dependencies. Currently I can see 52k+ commits in a single push.

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy sure will remove the dependencies

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy I have removed all the dependencies .You could check now .

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
remove the ds_store files also

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy sure will remove this 
Thanks 👍

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy Deleted the .ds_store one .you could check now 
thanks in advance .
Happy Hacking

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
