### PR TITLE
Added Strong Pass Extension

### PR DESCRIPTION
**Pull request by Asymtode712**
# Description

Strong Password Generator aims to solve the problem of users needing to create strong, unique passwords for their online accounts by providing an easy-to-use tool for generating secure and strong passwords.

Fixes:  #197

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [ ] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy Please review my PR and merge it if it is good to go

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy I guess you were instructed to only change labels for workflows not these issues

**Comment by Sulagna-Dutta-Roy** [comment]
Yeah, I'm working on this. Thanks for the patience. 
It's messed because of some new PRs

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy mam,

I know you have recieved instructions so you have removed level3/level2 label but you can assign me 'level1' label for workflow PRs

"It has been communicated before that dont give level more than 1 or no levels." This was the message conveyed so according to it, 'level1' label can be granted right?

The final decision is still yours but i just reminded you

Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check again 🙏🙏

**Pull request merged**
