### PR TITLE
Created TextToSpeech Extension Files

### PR DESCRIPTION
**Pull request by prasad-chavan1**
# Description

Text to speech extension just for simplicity sake :)

Fixes:  #111 

## Type of change

New Dir

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by prasad-chavan1** [comment]
@Sulagna-Dutta-Roy review & merge

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Text To Speech/your files. 
Also add script files for the extensions.

**Comment by prasad-chavan1** [comment]
> Change the directory name: Text To Speech/your files. Also add script files for the extensions.

already added scripts file

**Comment by prasad-chavan1** [comment]
@Sulagna-Dutta-Roy I deleted that dir and reuploaded and also updated scripts file now checkout review and merge

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
