### PR TITLE
Interactive Story telling extension.

### PR DESCRIPTION
**Pull request by taneeshaa15**
Extension:

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/157527085/1b2ec788-45cd-4c31-8846-8d88ffd63b9e

Hi @Sulagna-Dutta-Roy ,
I hope you're doing well. I've addressed the issue #1588 and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Also, please check the level assigned according to my PR before merging.

Best regards,
Tanisha Garg

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Interactive Story Telling/your files @taneeshaa15

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy You want me to remove gaming extension from the title in extension?

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please review it again.

**Comment by Sulagna-Dutta-Roy** [comment]
Still not changed kindly do the change as per the above Instructions @taneeshaa15

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy ma'am I am sorry but I can't properly understand what ypu want me to do.
May you please explain it to me?

**Comment by Sulagna-Dutta-Roy** [comment]
Directory== Folder name

**Comment by taneeshaa15** [comment]
Okay ma'am

**Pull request closed without merging**
