### PR TITLE
Add Crack code folder ##2052 

### PR DESCRIPTION
**Pull request by Aditijainnn**
# Description
This game is a beginner friendly game.
Crack the code with the hints given to you and according to the rules and enjoy the game

How to play?
Crack the code according to the given rules to you.
Enter the code and check it.
To check the answer, what it will be. Click on the show answer button.

Fixes: #2052

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

345141109-85c3033a-d8f0-422c-a673-492d1f9da0bb

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name as: Crack Code/your files @Aditijainnn 
Also add the manifest files

**Comment by Aditijainnn** [comment]
> Change the directory name as: Crack Code/your files @Aditijainnn Also add the manifest files

ok

**Comment by Aditijainnn** [comment]
> Change the directory name as: Crack Code/your files @Aditijainnn Also add the manifest files

made the changes

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Crack Code/your files @Aditijainnn

**Comment by Aditijainnn** [comment]
> Change the directory name: Crack Code/your files @Aditijainnn

done

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Why there is another folder called 'your files'?
I guess I didn't told about your files folder.

It means you files needs to be added in the crack code folder only. 
Directory name should be: Crack Code/your files 

Check the capital small letters that I have mentioned @Aditijainnn

**Comment by Sulagna-Dutta-Roy** [comment]
Leave it. I merged this 
But check the comments above

**Pull request merged**
