### PR TITLE
Fixes #159 : Chatbot

### LINKED ISSUE #159: Chatbot JS Extension
**Is your feature request related to a problem? Please describe.**
<ul>
<li>Currently, integrating a chatbot into a website requires substantial technical expertise. Existing solutions often involve complex setup processes and configuration, making it difficult for developers, especially those with limited experience, to implement an effective chatbot.</li>
<li>Websites often struggle to maintain user engagement and provide instant support. Without an easily deployable chatbot, users might leave the site without finding the information they need, leading to lower user satisfaction and higher bounce rates.</li>
<li> Many available chatbot solutions lack the flexibility to be easily customized to fit specific business needs and branding requirements. Users need a tool that allows for easy customization of responses, appearance, and behavior to align with their website’s goals and aesthetics.</li>

**Describe the solution you'd like**
<ul>
<li>Users should have the ability to easily define and update the chatbot’s responses through a user-friendly interface or a configuration file.</li>
<li>This includes setting up pre-defined responses, creating decision trees, and enabling the chatbot to handle common user queries effectively.</li>
<li>In this chatbot, users will be able to ask any question and receive instant responses. This chatbot has an elegant and responsive user interface, ensuring a seamless experience across various devices.</li>
</ul>

**Additional context**
The Chatbot Extension should seamlessly integrate into any browser, and must have a clean UI, in order to provide a great User Experience.

What problem is this feature trying to solve?
This feature is trying to solve the users problem of the lack of a proper integrable chatbot, which can be used as an extension, as well as can be integrated into their websites.

How do we know when the feature is complete?
The feature will be completed when the users will be able to ask questions and get a reply from the chatbot, as well as customize their questions any number of times, thus ensuring a great User experience.

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
# Description

This is a chatbot JS extension, made to make people's lives easier. They don't have to visit to AI sites anymore. All they have to do is to click on this extension, and enter their prompt.

Fixes:  #159 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot 2024-05-18 121645

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by gssocagent** [comment]
Hello @Sulagna-Dutta-Roy ,
Kindly remove the labels as GSSoC '24 guidelines won't allow copy paste code. 
`@Sambit-Mondal` lot of PR got merged in your project.

### Screenshot -
image

Kindly check the above screenshot PR and remove the labels if you think it's a beginner task or it's copy pasted.

GSSoC Team also raised a mail regarding this on your mail that you are giving useless levels to the contributors kindly add proper labels.

Documentation - gssoc
Entry Level Code - level1
Mid Level Code - level2
Adv Code - level3

Kindly distribute the code levels like this. Also remove the labels of all Merged PR which have copy pasted code because GSSoC Team will check and can ban the `Project Admin` including the `Contributor`.


Hope you got the point.

**Comment by Sulagna-Dutta-Roy** [comment]
Thanks for raising this. I will check. Apologies

**Comment by gssocagent** [comment]
We are just checking the top 100 contributors now to maintain hardworking ranks up.
Kindly remove  the labels and add and `invalid` label here.

**Comment by Sulagna-Dutta-Roy** [comment]
Okay sure. Working on this

**Comment by gssocagent** [comment]
Just give `invalid` label not even `level1` is allowed

**Comment by Sulagna-Dutta-Roy** [comment]
Can you please check now?

**Comment by gssocagent** [comment]
Yes. It's fine now also check other PRs too.

**Comment by Sulagna-Dutta-Roy** [comment]
Sure

**Pull request merged**
