### PR TITLE
Added String to integer calculator

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Description

Added String to integer calculator

Fixes:  #1699 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Before creating any PR should check what's the project about. Also this is a extensions repo where people contributing extensions only. 
Your project is a sample project not an extension @Saipradyumnagoud 

Also change the directory name as: String Integer/your files

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy  yes i have made the changes please check

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Directory name should be: String Integer/your files 
Add manifest file here

**Comment by Saipradyumnagoud** [comment]
@Sulagna-Dutta-Roy  changes made

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy changes made

Directory name still not changed

**Comment by Saipradyumnagoud** [comment]
> > @Sulagna-Dutta-Roy changes made
> 
> Directory name still not changed 

changed

**Comment by Saipradyumnagoud** [comment]
image

i have changed it to string integer

**Comment by Sulagna-Dutta-Roy** [comment]
Check the project description for directory name. Still not changed

**Comment by Saipradyumnagoud** [comment]
> roject description for directory

can i connect you on discord? please

**Comment by Saipradyumnagoud** [comment]
> Check the project description for directory name. Still not changed

can you once please provide screen shot

**Comment by Saipradyumnagoud** [comment]
image
I have changed it @Sulagna-Dutta-Roy

**Review by Saipradyumnagoud — COMMENTED** [review]
Changed the file name

**Comment by Sulagna-Dutta-Roy** [comment]
String integer ❌ 
String Integer ✅ 

Every project is following this format @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
> String integer ❌ String Integer ✅
> 
> Every project is following this format @Saipradyumnagoud

oky i will updated in 5 min

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by Saipradyumnagoud — COMMENTED** [review]
Made the required  changes

**Pull request merged**
