### PR TITLE
Frogger game

### PR DESCRIPTION
**Pull request by mahek0620**
# Description

Lives
Frogger starts with 6 lives and should lose a life whenever it is hit by a vehicle or lands in the water
Timer
The player has 30 seconds to get Frogger to the end bank. Display the timer as a reverse progress bar
Timer resets when player gets to the end bank or dies
Score
Each time Frogger makes it to the end bank
Mobile and touchscreen support
Allow the game to be scaled down to a phone size. 

image

Fixes:  #1560 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by mahek0620** [comment]
@Sulagna-Dutta-Roy as this is not a basic game kindly update the labels if you find it relevant

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Frogger Game/your files
Where is manifest files? @mahek0620

**Comment by mahek0620** [comment]
@Sulagna-Dutta-Roy Keeping in mind the difficulty level and more features please update the labels

**Comment by mahek0620** [comment]
image
manifest.json is already added and html file contains js code

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
