### PR TITLE
Solved #1967- Solar system simulation

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)
#1967

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
Kindly review and merge

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Directory name: Solar System Stimulation/your files 
@Aditi22Bansal

**Comment by Aditi22Bansal** [comment]
@Sulagna-Dutta-Roy 
What changes has to be done?

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy What changes has to be done?

Change the directory name as per the above

**Pull request closed without merging**
