### PR TITLE
added game Cut the Rope

### PR DESCRIPTION
**Pull request by tanyagupta01**
# Description
Added the game Cut the Rope as a browser extension.

Fixes:  #1479

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/156044894/57fd015e-0b1a-455c-9d11-d8cda0bb511c

### CODE REVIEW

**Comment by tanyagupta01** [comment]
@Sulagna-Dutta-Roy kindly review this PR.

**Comment by tanyagupta01** [comment]
I have reduced a few extra files. The rest are assets which were required in this game since there were a lot of images, videos etc used. @Sulagna-Dutta-Roy Kindly review it.

**Comment by tanyagupta01** [comment]
@Sulagna-Dutta-Roy ma'am now there is 1 html, 3 css, 4 js files and the remaining all are only for images, videos and audio.
Kindly review.

**Review by Sulagna-Dutta-Roy — COMMENTED** [review]
Kindly avoid this type of large projects with full of dependencies. The repository can be break. Thanks @tanyagupta01

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by tanyagupta01** [comment]
@Sulagna-Dutta-Roy Okay. I will keep that in mind.

**Pull request merged**
