### PR TITLE
added feature download button in QR GENERATE

### PR DESCRIPTION
**Pull request by P-lavanya16**
# Description

added a feature download button to get qr download 

Fixes:  #180

Screenshot (82)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
I've checked this pull request. But there's some submodules which need to be removed.
Also please check the pull request template.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly remove the submodules.

**Comment by P-lavanya16** [comment]
git submodule
fatal: no submodule mapping found in .gitmodules for path 'GGExtensions'
-->but its saying there are no submodules how can i resolve it

**Comment by P-lavanya16** [comment]
@Sulagna-Dutta-Roy  i have deleted and done from first as i have got trouble with git repository .Sorry for inconvenience for closing

**Pull request closed without merging**
