### PR TITLE
Stress management tip extension added

### PR DESCRIPTION
**Pull request by Harleen-786**
# Description

This pull request introduces a new feature to enhance our application with stress management tips. The primary aim is to provide users with helpful advice and techniques to manage and reduce stress effectively. The changes include:

Fixes:  #573 

## Type of change

- [ X] New feature (non-breaking change which adds functionality)

# Checklist:

- [ X] I have made this from my own
- [ X] I have taken help from some online resourses 
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-06-05 at 12 10 09 AM

I am contributing upon Gssoc24

### CODE REVIEW

**Comment by Harleen-786** [comment]
@Sulagna-Dutta-Roy I have added stress management tips extension please check it

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name as: Stress Management Tips/your files 
Also add the script files because currently not showing as an extension

**Comment by Harleen-786** [comment]
@Sulagna-Dutta-Roy done with the requested changes please check and acceot the pull reuqest

**Comment by Harleen-786** [comment]
@Sulagna-Dutta-Roy please check I hve done all the requested changes

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Mentor is Inactive. Please patience I will check all the PRs

**Pull request merged**
