### PR TITLE
Baseball Game is added

### PR DESCRIPTION
**Pull request by pallasivasai**
# Description

#2261 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Baseball Game - Google Chrome 10-07-2024 15_12_57

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add manifest files @pallasivasai

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly respond @pallasivasai 
Else I will assign this Issue to other contributor or cancel this PR

**Comment by pallasivasai** [comment]
no I will a new PR!

**Comment by pallasivasai** [comment]
https://github.com/Sulagna-Dutta-Roy/GGExtensions/pull/2384/files#diff-c3bff6cba4dc23ceccdae5d4c4a38a5faab7b5839544e9223724c846e738e924

please ref my new PR

**Pull request closed without merging**
