### PR TITLE
Enhanced the UI and also Added a preloader

### PR DESCRIPTION
**Pull request by Mooosiee**
# Description

This is what it initially looked like
Screenshot 2024-05-23 011100
i changed the UI:added a colour palette and also aligned the body as u can see the height was not aligned
Screenshot 2024-05-23 005727
Also added a preloader when internet speed is slow this will be visible
image

Fixes:  #378 

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x ] I have made this from my own

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add script files.

**Comment by Mooosiee** [comment]
i removed the other files only the extension files remain

**Comment by sarthak-stranger** [comment]
@Mooosiee ,
• Place the Position of this quiz form in Center and also increase the size of it.
• Color which you are using is not attractive and also use image or color in  background to improve UI.
• You can refer colors through Templates.

**Comment by Mooosiee** [comment]
@sarthak-stranger Oh ok I'll look into it!

**Pull request closed without merging**
