### PR TITLE
Add Hextris - New Game

### PR DESCRIPTION
**Pull request by katarianikita2003**
[New Game] - Hextris
Fixes: #1933 
# Description
# **Game_Name** 
Hextris
## **Description 📃**
The goal of Hextris is to stop blocks from leaving the inside of the outer gray hexagon.

## **Functionalities 🎮**
- You have to rotate the inner hexagon using left or right arrow keys to match the color of the incoming block to that of the already present block.
- Blocks will be cleared once 3 or more blocks of the same color touch and you get points.
- You have to prevent the blocks from touching the boundary of the outer gray hexagon.

## **How to play? 🕹️**
- Press the right and left arrow keys to rotate the inner hexagon. Press the down arrow to speed up the block falling.
- Clear blocks and get points by making 3 or more blocks of the same color touch each other.
- Time left before your combo streak disappears is indicated by the colored lines on the outer hexagon.

Fixes:  #1933 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-06-25 105713

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add the Issue no. 
Please retain yourself high amount of large files for this repo. Delete all the binary/dependencies only code files will be helpful. 
Add manifest files also

**Comment by katarianikita2003** [comment]
issue #1933

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Delete all the package dependencies as I have checked the code and fully working. My repo can be break with large dependencies @katarianikita2003

**Comment by katarianikita2003** [comment]
I don't understand which dependencies you are talking about. If I delete them then the code won't run @Sulagna-Dutta-Roy , Can you please tell me?

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Only code files are enough to contribute after reviewing it

**Pull request merged**
