### PR TITLE
Want To Add Dog Show Game #1511

### PR DESCRIPTION
**Pull request by nishant0708**
Want To Add Dog Show Game #1511

-ADDED Dog Show  folder 

Fixes:  #1511 

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://nishant0708.github.io/DOG-GAME_main/

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Where is manifest.json file

**Comment by nishant0708** [comment]
hey @Sulagna-Dutta-Roy It don't have one . As it was pure js , html  project so it don't need one .And it does not require any  library so i never made one

**Comment by Sulagna-Dutta-Roy** [comment]
If not then I can't accept this pull request. Because I mentioned every time this is an extension repository. 
Some of the games I received had manifest files.

**Comment by nishant0708** [comment]
Wait @Sulagna-Dutta-Roy  let me create one.

**Comment by nishant0708** [comment]
Hey @Sulagna-Dutta-Roy sorry for inconvenience please check it now

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
