### PR TITLE
Crypto wallet and currency tracker

### PR DESCRIPTION
**Pull request by taneeshaa15**
Hi @Sulagna-Dutta-Roy ,
I hope you're doing well. I've addressed the issue #1590 and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Please review my last made PR.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
For every project giving the same feedback to change the directory. 
Ctypto Wallet/your files

**Comment by Sulagna-Dutta-Roy** [comment]
@taneeshaa15 any update?

**Comment by taneeshaa15** [comment]
Mam actually in my github, directory is fine so I cant change it.
I am so sorry for that, I cant do anything more in this issue.
Still I can just request you to merge these issuesand I will take the utmost care from next time.
It is already changed as you said.

**Comment by Sulagna-Dutta-Roy** [comment]
I didn't said it's changed, if it's changed than I should approve this earlier. So I commented for the update. 
Anyway I am closing this PR because can't accept this without a change. If you want to make another PR for this then I will check. Thanks @taneeshaa15

**Pull request closed without merging**
