### PR TITLE
added palindrome checker

### PR DESCRIPTION
**Pull request by samarsajad**
# Description

A palindrome checker to check whether a number ,word or sentence is a palindrome.

Fixes:  #1704 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review  my pull request @Sulagna-Dutta-Roy

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by sanjay-kv** [comment]
Hi @samarsajad 

if you are contributing the extension this repo has limitation of 150 points as per guidelines
https://github.com/GSSoC24/Contributor/tree/main/gssoc-guidelines
image

will be removing extra points to make sure fair leaderboard.

**Comment by samarsajad** [comment]
> Hi @samarsajad 
> 
> if you are contributing the extension this repo has limitation of 150 points as per guidelines
> https://github.com/GSSoC24/Contributor/tree/main/gssoc-guidelines
> image
> 
> will be removing extra points to make sure fair leaderboard. 
> 

I didn't know about it and when I came to know about this I stopped contributing in this repo. If you could please consider these extra 170 points that'd be really helpful.

**Comment by sanjay-kv** [comment]
image
guidelines has been updated on June 10th and has been communicated via discord, mail, and newsletter. 

Im sorry for reducing points, I gave you 200 points instead of 150 points. 

This is the toughest discission we made this year to limit contribution, these selected repo are meant to be for the beginners.
unless you contribute anything technical side limitation does not apply.

We know there is spams going on we are working best to solve it.
https://github.com/GSSoC24/Contributor/discussions/490
https://github.com/GSSoC24/Contributor/discussions/492
attaching few of the thread we made on the same.

Top 50 people will go through the review this week again so if any spams will reduce the points.

**Comment by Sulagna-Dutta-Roy** [comment]
Thank you @sanjay-kv

**Comment by samarsajad** [comment]
> image
> guidelines has been updated on June 10th and has been communicated via discord, mail, and newsletter. 
> 
> Im sorry for reducing points, I gave you 200 points instead of 150 points. 
> 
> This is the toughest discission we made this year to limit contribution, these selected repo are meant to be for the beginners.
> unless you contribute anything technical side limitation does not apply.
> 
> We know there is spams going on we are working best to solve it.
> https://github.com/GSSoC24/Contributor/discussions/490
> https://github.com/GSSoC24/Contributor/discussions/492
> attaching few of the thread we made on the same.
> 
> Top 50 people will go through the review this week again so if any spams will reduce the points.

I'd 1175 points before & now I've 885 which means 290 points have been deducted from this repo. I only had 320 points from this repo . Can you please recheck if there's been a mistake . Also, lemme know if I'm wrong with my calculations. Thanks @sanjay-kv

**Comment by sanjay-kv** [comment]
image
you were right, i will be giving 200 points soon, 

sorry about the mistake, it will take 2 days, could you remind me again after 2 days.

**Comment by sanjay-kv** [comment]
[issue -fix.pdf](https://github.com/user-attachments/files/16237316/issue.-fix.pdf)
Done

**Pull request merged**
