### PR TITLE
Screen pet game #752

### PR DESCRIPTION
**Pull request by nisargaa20**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)
Screen Pet game is an event-based program, which means the functions it performs and the order in which it performs all functions is dependent on user input. In such programs, user input can take any form, such as keypresses and mouse clicks.

Fixed :#752

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screen Pet - Google Chrome 31-05-2024 09_28_52
Screen Pet - Google Chrome 31-05-2024 09_29_07
Screen Pet - Google Chrome 31-05-2024 09_29_28
Screen_Pet_Game
Screen Pet - Google Chrome 31-05-2024 09_28_49

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Check your directory, I can see you've added your project in the world clock extension.
Kindly follow the guidelines mentioned the repository.
If should be Screen Pet Game/your files 
Every Project have their own folder @nisargaa20

**Comment by nisargaa20** [comment]
@Sulagna-Dutta-Roy I have changed it

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Screen Pet Game/your files
It's not changed still

**Comment by nisargaa20** [comment]
@Sulagna-Dutta-Roy sorry for the inconvenience. Kindly check it out now

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
