### PR TITLE
add hcf calculator

### PR DESCRIPTION
**Pull request by ANKeshri**
# Description

add hcf calculator

Fixes:  #2374 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] I have made this from my own
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/user-attachments/assets/bf1b4893-fbf6-423c-908a-04032495e7f4

### CODE REVIEW

**Comment by ANKeshri** [comment]
@Sulagna-Dutta-Roy PLEASE review and merge my pr

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: HCF Calculator/your files

**Comment by ANKeshri** [comment]
> Change the directory name: HCF Calculator/your files

@Sulagna-Dutta-Roy doing it

**Comment by ANKeshri** [comment]
@Sulagna-Dutta-Roy done

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
