### PR TITLE
Added Image Compressor

### PR DESCRIPTION
**Pull request by TheNikhilRaj**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #249 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
capture8

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name as: Image Compressor/your files

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Still the directory name not changed. Also for a suggestion kindly make a branch before make a PR because master to master push is not a healthy practice @TheNikhilRaj

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy  can you remove this directory and clear all that i have made changes because it very difficult to make changes please help out this so i can add fresh new file !

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy  I Added the new file "Image Compressor" you can check it.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Currently not showing as an extension. Where is manifest files?

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by TheNikhilRaj** [comment]
Hii @Sulagna-Dutta-Roy 
My commited is approved so, how can i show my points and also my name is not mentioned in the leaderboard.
can you please help me to get my points because this is my first contribution.

**Comment by Sulagna-Dutta-Roy** [comment]
Check the leaderboard again. Labels are mentioned so it will show

**Comment by TheNikhilRaj** [comment]
Thank You @Sulagna-Dutta-Roy 
I got 25 points !
🙂

**Pull request merged**
