### PR TITLE
Eyes strain reducer

### PR DESCRIPTION
**Pull request by ankit1576**
# Description
Creted blue light filter

Fixes:  #2523 

https://github.com/user-attachments/assets/84fa6c72-f1da-4a1f-95d2-3882c935598d

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
How many points did you earn from my repo?@ankit1576

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Blue Light Filter/your files @ankit1576

**Comment by ankit1576** [comment]
> How many points did you earn from my repo?@ankit1576 

20 points

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Eye Strain Reducer/your files @ankit1576

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
