### PR TITLE
Added Hexawrap Game

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#2504

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #2504 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### Game

https://github.com/user-attachments/assets/fc506d41-486c-4040-bafb-5f635bcd93dc

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Review by Sulagna-Dutta-Roy — COMMENTED** [review]
It's not recommended to add 10+files in a single project with heavy dependencies which can break the repo. @Anjaliavv51

**Review by Sulagna-Dutta-Roy — COMMENTED** [review]
Thankyou for contributing here

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy also assign me this PR.

**Pull request merged**
