### PR TITLE
Jokes Xpress Extension

### PR DESCRIPTION
**Pull request by Ayushvishwakarma04**
# Description

This PR adds a new feature as the Joke Express extension, as requested in issue #21. It implements the ability to fetch and display a random joke from the JokeAPI in the extension popup.

Fixes:  #21

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
ScreenShot_another
ScreenShot

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Hello. 
Please make a folder and arrange the files like this. Project Name/your files 
It should be: Jokes Xpress Extension/all files

**Comment by Ayushvishwakarma04** [comment]
Hello, I hope this message finds you well. I wanted to share that I've successfully resolved the issue by relocating all the files into the Jokes Xpress Extension directory. If there's anything else, please let me know.

**Comment by Ayushvishwakarma04** [comment]
> Hello. Please make a folder and arrange the files like this. Project Name/your files It should be: Jokes Xpress Extension/all files

Hello, I hope this message finds you well. I wanted to share that I've successfully resolved the issue by relocating all the files into the Jokes Xpress Extension directory. If there's anything else, please let me know.

**Comment by Sulagna-Dutta-Roy** [comment]
Can you please change the folder name. As I mentioned above.

**Comment by Ayushvishwakarma04** [comment]
> Can you please change the folder name. As I mentioned above.

Changed the folder name from Jokes_Xpress_Extension/all files to Jokes Xpress Extension/all files.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Not able to merge it because of conflicts. Can you please check

**Comment by Ayushvishwakarma04** [comment]
> Not able to merge it because of conflicts. Can you please check

Thanks for your patience. The conflict is resolved now.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
