### PR TITLE
Add Find Keys

### PR DESCRIPTION
**Pull request by katarianikita2003**
# Description
# Find Keys-Game
=====================
## Introduction

A minimalist horror game 
You're locked in the basement.

Find the keys to unlock the door to your freedom.

## How to Play

- Look around for key using mouse
- Click W A S D key to move
- For instructions click on help given below

Fixes:  #(issue no.)
#1909 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-07-24 123509

### CODE REVIEW

**Comment by katarianikita2003** [comment]
Working Video

https://github.com/user-attachments/assets/22c89a4b-e8f2-45df-8cfe-90bdd8312fe1

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned? 150 points done? @katarianikita2003

**Comment by katarianikita2003** [comment]
From your project or overall?

**Comment by Sulagna-Dutta-Roy** [comment]
> From your project or overall?

From my repo only. @katarianikita2003

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by katarianikita2003** [comment]
> > From your project or overall?
> 
> From my repo only. @katarianikita2003

No

**Comment by Sulagna-Dutta-Roy** [comment]
> > > From your project or overall?
> > 
> > From my repo only. @katarianikita2003
> 
> No

You have merged some PRs in my repo. What are the scores you received? Kindly check the leaderboard and let me know because my repo has score limitations. @katarianikita2003

**Comment by katarianikita2003** [comment]
> > > > From your project or overall?
> > > 
> > > 
> > > From my repo only. @katarianikita2003
> > 
> > 
> > No
> 
> You have merged some PRs in my repo. What are the scores you received? Kindly check the leaderboard and let me know because my repo has score limitations. @katarianikita2003

My 8 PR'S are merged by you some of them are level 1 and some are level 2 
So, my be it can be around 150

**Comment by Sulagna-Dutta-Roy** [comment]
> > > > > From your project or overall?
> > > > 
> > > > 
> > > > From my repo only. @katarianikita2003
> > > 
> > > 
> > > No
> > 
> > You have merged some PRs in my repo. What are the scores you received? Kindly check the leaderboard and let me know because my repo has score limitations. @katarianikita2003
> 
> My 8 PR'S are merged by you some of them are level 1 and some are level 2 
> So, my be it can be around 150

Yes. My repo has some restrictions to 150. Thank you for all the contributions.

**Comment by katarianikita2003** [comment]
> > > > > > From your project or overall?
> > > > > 
> > > > > 
> > > > > From my repo only. @katarianikita2003
> > > > 
> > > > 
> > > > No
> > > 
> > > 
> > > You have merged some PRs in my repo. What are the scores you received? Kindly check the leaderboard and let me know because my repo has score limitations. @katarianikita2003
> > 
> > 
> > My 8 PR'S are merged by you some of them are level 1 and some are level 2
> > So, my be it can be around 150
> 
> Yes. My repo has some restrictions to 150. Thank you for all the contributions.

Thank You : )

**Pull request merged**
