### PR TITLE
ADDED RED RUNNER GAME

### PR DESCRIPTION
**Pull request by TheNikhilRaj**
# Description

Red Runner
Red Runner, Awesome Platformer Game.

It is now free and open source and always will be. 👏 🎉

Fixes:  #2248 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
redrunner

@Sulagna-Dutta-Roy

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
This PR is not acceptable at all. I can't able to review it because of lagging issues. also 1.4k+ files for a project hightly not acceptable in any open source program. 
If I merge this my repository will break, so I can't take a risk for other contributors @TheNikhilRaj 

Expecting your view on this. Else I will close this PR Immediatly. Thanks @TheNikhilRaj

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this PR, as no update received on this. Also 1.4k+ files highly unacceptable

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy no I'm still working on it..

**Comment by TheNikhilRaj** [comment]
> This PR is not acceptable at all. I can't able to review it because of lagging issues. also 1.4k+ files for a project hightly not acceptable in any open source program. If I merge this my repository will break, so I can't take a risk for other contributors @TheNikhilRaj
> 
> Expecting your view on this. Else I will close this PR Immediatly. Thanks @TheNikhilRaj

close it! @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Thanks, for Informing

**Pull request closed without merging**
