### PR TITLE
Added VPN Extension

### LINKED ISSUE #2509: Add VPN Extension
## Is your feature request related to a problem? Please describe.
I'm always frustrated when my internet activities are not private and secure, and I cannot access content that is region-locked. I also find it inconvenient to manually set up a VPN each time I want to use one.

## Describe the solution you'd like
I would like a VPN extension that integrates seamlessly with my browser. The extension should provide a simple on/off toggle for connecting to a VPN server, options to choose different server locations, and ensure that all browser traffic is encrypted. Additionally, the extension should have features like automatic reconnection if the VPN drops, and a kill switch to stop internet traffic if the VPN connection fails.

## Describe alternatives you've considered
- **Standalone VPN Applications**: These require manual setup and are not as convenient as a browser extension.
- **Browser Incognito/Private Mode**: This does not encrypt traffic or provide access to region-locked content.
- **Proxy Extensions**: These often do not offer the same level of encryption and privacy as a VPN.

### What problem is this feature trying to solve?
This feature is trying to solve the problem of ensuring internet privacy and security directly within the browser, making it easier for users to protect their online activities and access content that may be restricted based on geographic location.

### How do we know when the feature is complete?
- The extension has a user-friendly interface with a clear on/off toggle for the VPN.
- Users can select from multiple server locations.
- All browser traffic is encrypted when the VPN is active.
- The extension includes automatic reconnection and a kill switch feature.
- The extension is tested and works across major browsers (Chrome, Firefox, Safari, Edge).
- Positive user feedback indicating ease of use and enhanced online security and accessibility.
- 
@Sulagna-Dutta-Roy, could you please assign me this issue under GSSOC'24

### PR DESCRIPTION
**Pull request by sreevidya-16**
# Description

Added VPN Extension

Fixes:  #(issue no.)
Fixes #2509 issue

## Type of change
Adds VPN Extension to website

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add manifest files @sreevidya-16 
Also reducing the level1

**Comment by sreevidya-16** [comment]
I updated, please take a view of this PR, @Sulagna-Dutta-Roy

**Comment by sreevidya-16** [comment]
@Sulagna-Dutta-Roy, Review this PR

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: VPN Extension/your files. 
Add manifest files

**Pull request closed without merging**
