### PR TITLE
gredient issue solved

### PR DESCRIPTION
**Pull request by Yashgabani845**
# Description

All directional buttons where not working because of in Chrome extension 
coder has provided onclick fucntion
and it was giving this error
Screenshot (209)

i have use eventlistner and rewruite few code 
and i made comment few part to understand better
now it is working smoothly

Fixes:  #541 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Currently ll buttons are worlking properly
Screenshot (210)

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  kindly revirw this PR
thank you

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  please assign me in PR my contribution is not counting in leaderboard

**Comment by Sulagna-Dutta-Roy** [comment]
In every PR i added all the correct levels kindly check the leaderboard at 7pm @Yashgabani845

**Comment by Yashgabani845** [comment]
no i just talk with sanjay sir he told me that PR also should be assigned

**Comment by Yashgabani845** [comment]
@Sulagna-Dutta-Roy  please check this out mam
Screenshot (218)

https://github.com/GSSoC24/Contributor/discussions/288?utm_source=substack&utm_medium=email

**Pull request merged**
