### PR TITLE
Added Hill Climb Racing Game!

### PR DESCRIPTION
**Pull request by TheNikhilRaj**
# Description

I MADE THIS GAME USING HTML AND JAVA SCRIPT.

Fixes:  #2335 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Capture2

@Sulagna-Dutta-Roy

### CODE REVIEW

**Comment by TheNikhilRaj** [comment]
@Sulagna-Dutta-Roy  
Please assign me.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
@TheNikhilRaj I guess you had 135 points earlier. Now 2 issues as level2 merged around 190 points you earned.
Only 1issue left as entry level project which is 10 points. So 200 will be complete. Thanks

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj I guess you had 135 points earlier. Now 2 issues as level2 merged around 190 points you earned. Only 1issue left as entry level project which is 10 points. So 200 will be complete. Thanks

@Sulagna-Dutta-Roy  135 + 50 = 185 
but i need my 5 point!

**Comment by Sulagna-Dutta-Roy** [comment]
Okay, sure

**Pull request merged**
