### PR TITLE
New Game:[Matching_Pair]

### PR DESCRIPTION
**Pull request by priyashuu**
# Description
The Matching Pairs Game is a fun and engaging memory game developed using HTML, CSS, and JavaScript. The game challenges players to match pairs of cards with identical images within a limited time. It offers a simple yet addictive gameplay experience, enhanced with a sleek user interface .

Fixes:  #2580

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Matching_Pair_Game

https://github.com/user-attachments/assets/ee15cd9d-e9c8-4516-9bbf-c65c9525fec3

### CODE REVIEW

**Comment by priyashuu** [comment]
Dear @Sulagna-Dutta-Roy ,

I hope you're well. Could you please **update** my **first pull request's** contribution level from **Level 1 to Level 3**? This change would help me on the **leaderboard**, and I appreciate your understanding .I am eager to contribute more to the project; however, I am currently facing time constraints.

Thank you for your support.

**Comment by Sulagna-Dutta-Roy** [comment]
> Dear @Sulagna-Dutta-Roy ,
> 
> I hope you're well. Could you please **update** my **first pull request's** contribution level from **Level 1 to Level 3**? This change would help me on the **leaderboard**, and I appreciate your understanding .I am eager to contribute more to the project; however, I am currently facing time constraints.
> 
> Thank you for your support.

Entry Level: Level1
Intermediate: Level2
Advanced: Level3

Most of the game project is copied from another repository. So I just merged in the lower level. The gssoc team will check and update accordingly. Thanks

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Matching Pairs/your files @priyashuu

**Comment by priyashuu** [comment]
Dear @Sulagna-Dutta-Roy 

I have completed the requested changes. I want to clarify that I am the contributor of that repository you are referring to; it is not copied from anywhere else. I apologize for any misunderstanding. Please proceed as you see fit.
Let me know if there's anything else you want to change!

**Comment by Sulagna-Dutta-Roy** [comment]
> Dear @Sulagna-Dutta-Roy 
> 
> I have completed the requested changes. I want to clarify that I am the contributor of that repository you are referring to; it is not copied from anywhere else. I apologize for any misunderstanding. Please proceed as you see fit.
> Let me know if there's anything else you want to change!

I didn't mention anyone. You can check my comment again. I will merge it by today EOD.

**Comment by priyashuu** [comment]
Ok , Thank you 🫡❤️

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
