### PR TITLE
Added levels to captcha generator

### PR DESCRIPTION
**Pull request by P-lavanya16**
# Description

i have added levels to captcha Generator 

Fixes:  #2568 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
How many points you earned from my repo currently? @P-lavanya16

**Comment by P-lavanya16** [comment]
This is the 3rd pr  I have done with this repo with a level 1

**Comment by P-lavanya16** [comment]
Screenshot (134)
these 2 prs and this one total 3 prs

**Comment by Sulagna-Dutta-Roy** [comment]
I wanted to know the scores only. Kindly check again @P-lavanya16

**Comment by P-lavanya16** [comment]
This repository gets 30 points to me as level 1 gives 10 points only

**Pull request merged**
