### PR TITLE
Added Western-aim game Extension

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
# Description
Added Western-aim game Extension

Fixes:  #750 added

adding a new game

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
deployment link : -https://ramakrushnabiswal.github.io/western-aim-game/

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by RamakrushnaBiswal** [comment]
@Sulagna-Dutta-Roy  mam please add assignee otherwise ii will face issue in point calculation

**Comment by Sulagna-Dutta-Roy** [comment]
It will show in the leaderboard. Kindly check

**Comment by RamakrushnaBiswal** [comment]
Thank you mam @Sulagna-Dutta-Roy

**Pull request merged**
