### PR TITLE
Touch No Fire Game Added.

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#2505

# Description

### 🎮 Game Request

Game logic and basic description
Game Rules!
* Eat the food to gain score
* Do not touch the fire
* The fire multiplies once with even scores
* If you stay idle, the fire won't do anything
* Do not touch the moving fire
* Please play using arrow keys

## Screenshot Section

image

## Demo Video Section

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/a88f676a-69c8-4cc9-b6e6-98e5fca1aa59

Fixes:  #2505 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

## Screenshot Section

image

## Demo Video Section

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/a88f676a-69c8-4cc9-b6e6-98e5fca1aa59

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add the manifest files @Anjaliavv51 
Reducing to the level1,as it's an entry level project

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy manifest files mean?

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy manifest files mean?

Currently the project is a simple project not an extension. So every project should have manifest files. Kindly check other merged PRs

**Comment by Anjaliavv51** [comment]
> > @Sulagna-Dutta-Roy manifest files mean?
> 
> Currently the project is a simple project not an extension. So every project should have manifest files. Kindly check other merged PRs

okay

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy can we make issue on the above game , to change the UI of the Game?

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy can we rise issue on the above game , to change the UI of the Game?

Nope, it's not possible. You can't raise this but can change the other contributor projects @Anjaliavv51

**Comment by Anjaliavv51** [comment]
> > @Sulagna-Dutta-Roy can we rise issue on the above game , to change the UI of the Game?
> 
> Nope, it's not possible. You can't raise this but can change the other contributor projects @Anjaliavv51

okay

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
> Add the manifest files @Anjaliavv51 Reducing to the level1,as it's an entry level project

@Sulagna-Dutta-Roy  ur request is done
please review the PR.

**Pull request merged**
