### PR TITLE
Copy and search extension

### PR DESCRIPTION
**Pull request by tat-tvam-asii**
# Description

Added Copy Search Extension

Fixes:  #(issue no.)

Issue #77 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (2)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by tat-tvam-asii** [comment]
> You're assigned to every Issues. Correct levels are already added. Kindly check the leaderboard at 7pm @tat-tvam-asii

image

Here

**Comment by Sulagna-Dutta-Roy** [comment]
Let me check with the GSSOC team. It seems new to us.
Kindly have patience, I will add everyone today. Thank you🙏🙏🙏 @tat-tvam-asii

**Comment by tat-tvam-asii** [comment]
> Let me check with the GSSOC team. It seems new to us. Kindly have patience, I will add everyone today. Thank you🙏🙏🙏 @tat-tvam-asii

Thank you. Just for reference :
image

**Comment by Sulagna-Dutta-Roy** [comment]
Thank you. I will try to assign everyone today.

**Pull request merged**
