### PR TITLE
Contributing under GSSOC'24. Added a game.

### PR DESCRIPTION
**Pull request by rugved0102**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-08-01 002501

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
At first: My repository is about extensions only. 
Secondly, not accepting any other projects over extensions. 
Raise a Issue first then open a pull request. 
Lastly I'm unable to accept this PR because this PR doesn't an extension. @rugved0102 
Kindly open a new Issue if relevant, then I will accept this

**Comment by mohitgedar** [comment]
@Sulagna-Dutta-Roy hey , this is not my PR, and I would like to point it out to you that many contributors are copying games from GameZone repo of gssoc and creating a PR in your repo of the same , some are even copying from others code.From the screenshot provided in the PR I can say there is a exact same game in GameZone repo

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy hey , this is not my PR, and I would like to point it out to you that many contributors are copying games from GameZone repo of gssoc and creating a PR in your repo of the same , some are even copying from others code.From the screenshot provided in the PR I can say there is a exact same game in GameZone repo

Thank you for letting me know. I will look into this and apologize for the wrong mention :)

**Comment by rugved0102** [comment]
There were some games in this repo so I thought mine will be good but I'm very sorry to cause you trouble @Sulagna-Dutta-Roy

**Pull request closed without merging**
