### PR TITLE
added audio player extension

### PR DESCRIPTION
**Pull request by Asymtode712**
# Description

The feature aims to solve the problem of needing a quick, accessible, and integrated solution for playing audio files without switching applications. It reduces the steps required to play an audio file and provides a more integrated browsing experience.

Fixes:  #402 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [ ] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy please review and merge this PR

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy This one also must be again  labelled 'level2' right?

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy I know you have recieved instructions so you have removed level3/level2 label but you can assign me 'level1' label for WORKFLOW PRs

"It has been communicated before that dont give level more than 1 or no levels." This was the message conveyed so according to it, 'level1' label can be granted right?

The final decision is still yours but i just reminded you

Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check before checking the levels

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy mam, 

I am referring to the PRs #223 #203 #205 #208 #218 #220 #222 #304 #347

**Comment by Asymtode712** [comment]
They are worth 'level1' contributions

**Comment by Sulagna-Dutta-Roy** [comment]
But we can add no levels right? As per the guidelines. I removed them

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy Please check the mail instructions again

"We found this particular person has created github action workflow,
It has been communicated before that dont give level more than 1 or no levels. "

it says like this, and so 'level1' can be granted

**Comment by Sulagna-Dutta-Roy** [comment]
I considered no levels for these issues. But okay, I will need to add level 1.

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy Thank you mam

**Comment by Asymtode712** [comment]
@Sulagna-Dutta-Roy Just add them as soon as you get free as these PRs are too old and many new PRs are on the way so you might forget about these

**Pull request merged**
