### PR TITLE
Earth Guardian game extension added

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
# Description

Earth Guardian is a remake of the classic Space shooter type of games, with 8-bit (pixel art) assets. This project used free assets (music and graphics) provided by [Jonathan So](https://jonathan-so.itch.io/),[KennyNL](https://kenney.nl/) and other sources, like Google images and [OpenGameArt](https://opengameart.org). This was a learning project. There will be some updates in the near future. Hope you like it, have fun!

Fixes:  #870 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Earth_Guardian

### CODE REVIEW

**Comment by Pujan-sarkar** [comment]
@Sulagna-Dutta-Roy  please check this pr , thank you .

**Comment by Pujan-sarkar** [comment]
@Sulagna-Dutta-Roy  i think the changes have done you can check it.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Pujan-sarkar** [comment]
@Sulagna-Dutta-Roy please assign this pr to me , then it will count in my leaderboard.

**Comment by Sulagna-Dutta-Roy** [comment]
@Pujan-sarkar It should show when the leaderboard will be updated. Assigning the PR is not required

**Pull request merged**
