### PR TITLE
Added Simon Game Extension

### PR DESCRIPTION
**Pull request by Mooosiee**
# Description

Created a google chrome extension of the simon game with a good UI i have added 2 audio files 1 for whenever the button flashes and the 2nd for when we press a wrong button so the wrong button audio will play also added a preloader for whenever the website takes time in loading and also added a start and rest button to smoothly start and reset the and also added a display for  the level or score after the game is over 
So i request you to label this a level 3 issue thank you!
Fixes:  #572 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
UI:
image

Preloader:
Screenshot 2024-06-05 161206

Game Demo:

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/140048632/b7ad7322-0b78-4ffd-b6bf-e8001cc14e5f

### CODE REVIEW

**Comment by Mooosiee** [comment]
@Sulagna-Dutta-Roy Hi could you please label this as level 3?

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change  the directory name: Simon Game/your files

**Comment by Mooosiee** [comment]
> Change the directory name: Simon Game/your files

@Sulagna-Dutta-Roy how do i do that? like where do i have to make this change im sorry i dont understand.

**Comment by Sulagna-Dutta-Roy** [comment]
I'm talking about the folder rename that you've added.

**Comment by Mooosiee** [comment]
> I'm talking about the folder rename that you've added.

oh ok!!

**Comment by Mooosiee** [comment]
@Sulagna-Dutta-Roy Changes done, Also would you please consider labelling this a higher level 
Thank you!

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
