### PR TITLE
Added weight calculator

### PR DESCRIPTION
**Pull request by harshmishra19**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I have added a weight conversion calculator for converting weight in kg to pounds and vice versa.

Fixes:  #390 

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x ] I have made this from my own
- [ x] I have taken help from some online resourses 
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/115486960/464cb5bd-1c75-4ae7-b919-69afcf39b75d

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please change the directory as per the format: Weight Calculator/your files

**Comment by harshmishra19** [comment]
The directory is in the correct format

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly Check the directory format again. It should be Weight Calculator

**Comment by harshmishra19** [comment]
@Sulagna-Dutta-Roy I have made the changes

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
