### PR TITLE
Add Winner Notification and Play Again Functionality to Rock Paper Scissors Game

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
# Description

This update introduces a feature that displays a popup message when either the user or the CPU wins 5 games. The popup announces the winner and includes a 'Play Again' button that resets the game scores and state. Additionally, the sound functionality has been removed as it is no longer required.

Fixes: #264

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-05-18 073641

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add script files as it's an extension repository.

**Comment by thevijayshankersharma** [comment]
@Sulagna-Dutta-Roy its already there you can check once again. Here I am able to add extension too

image

**Comment by Sulagna-Dutta-Roy** [comment]
Please add manifest.json file.

**Comment by thevijayshankersharma** [comment]
image

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
