### PR TITLE
Image to text extension

### PR DESCRIPTION
**Pull request by Nikuunj**
# Description

Image to Text Convert Extension

Fixes:  #604 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

@Sulagna-Dutta-Roy

### CODE REVIEW

**Comment by Nikuunj** [comment]
@Sulagna-Dutta-Roy

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Image to Text/Your files
Kindly delete dependencies. I can see 87+ files changed and 10k+ commits. Check the other PRs for reference.

**Comment by Nikuunj** [comment]
@Sulagna-Dutta-Roy

**Comment by Nikuunj** [comment]
@Sulagna-Dutta-Roy  ohk

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Create one directory as: Image To Text/your files

**Comment by Nikuunj** [comment]
@Sulagna-Dutta-Roy

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
