### PR TITLE
Custom Alert Warning Extension 

### PR DESCRIPTION
**Pull request by codercake**
**# Description**
Custom warning alert notification extensions are tools or add-ons that can be integrated into web browsers or web applications to provide personalized alert messages. These alerts can be useful for notifying users about various conditions, events, or updates.

**Fixes:  #1625** 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK\

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/117517206/8374421e-e909-4dad-9e93-527a55162769

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Delete the .vscode files and submodules folder here

**Comment by codercake** [comment]
> Delete the .vscode files and submodules folder here

done ✅

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Delete the submodules folder.

**Comment by codercake** [comment]
> Delete the submodules folder.

which submodules folder?

**Pull request merged**
