### PR TITLE
Added Admin Panel

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

Added Admin Panel 

Fixes:  #940

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by sanjay-kv** [comment]
image

This animation is repeated work, and level2 is not worth, as
image
both the commits changes done to index.css.
As the admin is not responsive and I don't have access , I will reducing this points form GGextention.

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv 
Sir, I have a bit of confusion regarding how working on the same file leads to duplicate work. For instance, the same CSS file might be attached to many pages, so how does this result in the same issue?

The issues you are discussing, #186 and #179, are completely different. In #186, I added animations to the cards, and I have uploaded a video demonstrating that. In #179, I added an opening animation for the hamburger menu. The files are the same because the CSS for both issues is written in the same file.

Sorry to say, sir, but this is not fair considering the time I have invested. On Codar Hub, my points were deducted. I have no problem with that, but when my fair points are deducted, it is not actually fair to me. Working on the same files does not lead to the same issues, as the changes I made have their own importance.

Please ensure that any deductions are made with proper inspection. As a contributor dedicating my whole time to these contributions, it is discouraging to have my points deducted for no reason.

**Comment by Ayushmaanagarwal1211** [comment]
> image
> 
> This animation is repeated work, and level2 is not worth, as image both the commits changes done to index.css. As the admin is not responsive and I don't have access , I will reducing this points form GGextention.

Sir i have a little bit confusion how working on same file leads to same work 
Like in one issue i added animation to the cards and on the other i added animation to the navbar 
The file is same because both the components the index.css file will be sued for the css 
Sir i have also uploaded a video considering the changes i did 
So please review this once again

**Comment by sanjay-kv** [comment]
Hi @Ayushmaanagarwal1211 
Im saying either this thing could be a combined change or only level1, 

Lets say I'm added hover animation to footer - level 2
hover animation to footer bug fixed - level 1
hover animation footer main page - level 2

in your profile these been happening a lot. so this adds up exponential scores.

**Comment by Ayushmaanagarwal1211** [comment]
> Hi @Ayushmaanagarwal1211 Im saying either this thing could be a combined change or only level1,
> 
> Lets say I'm added hover animation to footer - level 2 hover animation to footer bug fixed - level 1 hover animation footer main page - level 2
> 
> in your profile these been happening a lot. so this adds up exponential scores. and these hover animation can be added to n number of components, in opensource its not an issue, we have mentioned this in guidelines as well. this is a nice way to get more score. as level 2 is 25points that would be huge considering this animation

Ok sir ow i undertood

**Comment by Ayushmaanagarwal1211** [comment]
> > Hi @Ayushmaanagarwal1211 Im saying either this thing could be a combined change or only level1,
> > Lets say I'm added hover animation to footer - level 2 hover animation to footer bug fixed - level 1 hover animation footer main page - level 2
> > in your profile these been happening a lot. so this adds up exponential scores. and these hover animation can be added to n number of components, in opensource its not an issue, we have mentioned this in guidelines as well. this is a nice way to get more score. as level 2 is 25points that would be huge considering this animation
> 
> Ok sir now i undertood

**Comment by sanjay-kv** [comment]
I will check again this with my technical team and come back to you if found worth it, I will be adding back points.

**Comment by Ayushmaanagarwal1211** [comment]
> I will check again this with my technical team and come back to you if found worth it, I will be adding back points.

No sir No need i understood if that not correct i have no problem with that

**Pull request merged**
