### PR TITLE
Added Squid Game extension

### PR DESCRIPTION
**Pull request by tanyagupta01**
Fixes:  #1589 

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / 
Screenshot 2024-06-14 at 12 20 11 AM
DEPLOYMENT LINK
Screenshot 2024-06-14 at 12 20 19 AM

### CODE REVIEW

**Comment by tanyagupta01** [comment]
@Sulagna-Dutta-Roy Kindly assign this PR a higher label if possible according to the complexity of the code.

**Comment by Sulagna-Dutta-Roy** [comment]
Here I can see that most of the files are binary/Images. And you're adding games as an extension which might be considered but as per the repo description I added that people need to contribute apps. 
So I added Level1. Also I've assigned many Issues for today let me know your points from my repository so that I will consider it to level2. 


Many people copy pasting chatgpt codes so the review check is extremely challenging for us(core gssoc team) @tanyagupta01

**Comment by tanyagupta01** [comment]
@Sulagna-Dutta-Roy till now I don't have any points from your repository. 4 PRs were merged today so I am expecting 85 points tomorrow.

**Comment by Sulagna-Dutta-Roy** [comment]
Okay thank you 🙏

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
