### PR TITLE
Basketball game extension added

### PR DESCRIPTION
**Pull request by Nayanika1402**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #969 

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x ] I have made this from my own
- [ x ] I have taken help from some online resourses 
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot 2024-06-06 084017

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Delete the dependencies. Change the directory name as: Basketball Game/your files

**Comment by Nayanika1402** [comment]
Requested changes done @Sulagna-Dutta-Roy .Kindly review it.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add manifest.json files because currently not showing as an extension

**Comment by Nayanika1402** [comment]
@Sulagna-Dutta-Roy Sorry for the inconvenience.

**Comment by Nayanika1402** [comment]
@Sulagna-Dutta-Roy Kindly merge my pr.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
