### PR TITLE
Added: Dyslexic Reader Helper Extension

### LINKED ISSUE #1199: Add: Dyslexic Reader Helper Extension
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem. People with dyslexia often find it challenging to read standard text on digital platforms. The uniform text size, font, and color can make it difficult for them to distinguish and comprehend the words, leading to a frustrating and exhausting reading experience.

**Describe the solution you'd like**
I would like to propose a feature that allows users to adjust the font and the background colors within the Dyslexic Reader Helper extension. This feature should include a slider in the extension settings, enabling users to select their preferred font and background color.

**Describe alternatives you've considered**
An alternative could be a feature that automatically adjusts the text display based on scientifically proven settings that are known to aid dyslexic people in reading. However, as dyslexia affects people differently, a one-size-fits-all solution might not be effective for everyone.

**Additional context**

How do we know when the feature is complete?
Through the PR

### PR DESCRIPTION
**Pull request by kosuri-indu**
# Description

This change introduces a new feature in the Dyslexic Reader Helper that allows users to customize the text display according to their preferences. This includes options to adjust the dyslexic font, and background color. The motivation behind this change is to make digital platforms more accessible for people with dyslexia. By allowing them to customize the text display, we aim to reduce their reading difficulties and improve their overall digital experience.

Fixes #1199 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118645569/e77b97d4-427a-45d5-af0d-51a9f79f8922

### CODE REVIEW

**Comment by kosuri-indu** [comment]
@Sulagna-Dutta-Roy 
Please review this PR :)
Thank you

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Delete the package dependencies

**Comment by kosuri-indu** [comment]
@Sulagna-Dutta-Roy 
Could you please provide more details about which package dependencies you would like me to delete?

**Comment by kosuri-indu** [comment]
@Sulagna-Dutta-Roy 
The fonts folder contains TrueType Font (TTF) files for the lexie-readable and open-dyslexic-font fonts. These are used by your application to apply custom fonts. The other folders are just html, css and js files segregated as views, styles and scripts.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
