### PR TITLE
Monopoly Game Added

### PR DESCRIPTION
**Pull request by Damini2004**
# Description

Monopoly Game added.

Fixes:  #1864 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy  Can you increase the level as this is 1st contribution in this repo.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add the manifest files @Damini2004

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy  Added.

**Comment by Sulagna-Dutta-Roy** [comment]
I don't think this is your 1st contribution @Damini2004

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy Previous was my first contribution can you add level 2 there.

**Comment by Damini2004** [comment]
Kindly merege it mam.

**Comment by Sulagna-Dutta-Roy** [comment]
Level1: Entry level
Level2: Intermediate 
Level3: Advanced 

So project admins needs to check according to the guidelines. Everytime I can't consider the same. Also people sometimes copy from chatgpt. This is very crucial to change every levels until it's Important. @Damini2004

**Comment by Damini2004** [comment]
@Sulagna-Dutta-Roy sure mam,i consider your things.

**Pull request merged**
