### PR TITLE
[Bug] : ToDo JS Exrension Logic

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# Description

- Bug can be soved...

Fixes:  #1579 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

[Screencast from 2024-06-14 00-41-54.webm](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/121082414/9166290d-f716-479c-99b9-6bc4f9548e5f)

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
Hello @Sulagna-Dutta-Roy , i will finish it...

**Comment by Sulagna-Dutta-Roy** [comment]
> Hello @Sulagna-Dutta-Roy , i will finish it...

What?

**Comment by sivaprasath2004** [comment]
Todo List not working missing the logics, so i will fix it..

**Comment by sivaprasath2004** [comment]
@Sulagna-Dutta-Roy ,

### Before 

[Screencast from 2024-06-13 22-16-44.webm](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/121082414/1af655f2-a533-4901-966c-a1ed5d883d72)

### After

[Screencast from 2024-06-14 00-41-54.webm](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/121082414/9166290d-f716-479c-99b9-6bc4f9548e5f)

**Comment by Sulagna-Dutta-Roy** [comment]
Actually I'm not understanding. Did you complete this as per the above files?

**Comment by sivaprasath2004** [comment]
@Sulagna-Dutta-Roy ,
`ToDo JS Extension/scripts/script.js` file used for the `localStorage` logic if  Before run the program doesn't show the `todo list` and After i will change the program code to work `todo list`.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
