### PR TITLE
Fixes#149:Added extension to focus while browsing

### PR DESCRIPTION
**Pull request by akshbansal61203**
# Description

The Focus Mode: Distraction Blocker is a browser extension designed to enhance productivity by temporarily blocking access to social media and other distracting websites during designated work hours. This tool helps users stay focused on their tasks by preventing access to specified websites that often lead to procrastination and loss of productivity.
Distraction Blocker extension is a powerful tool to help users maintain productivity by blocking access to distracting websites during work hours.
I have attached screenshots of Focus mode extension before and after it's deployed. 

Fixes:  #149 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-05-16 at 5 28 53 PM
Screenshot 2024-05-16 at 5 28 16 PM
Screenshot 2024-05-16 at 5 28 03 PM

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please change the directory name: Browser Focus/your files

**Comment by akshbansal61203** [comment]
I have changed the directory name. Thank you

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
I checked the PR. Showing 45files added. 
Kindly check and push from the new branch. I can see master to master branch operations which is not a healthy practice.

Kindly open new PR and create a new branch for pull request. Thank you

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this PR because new PR is added correctly

**Pull request closed without merging**
