### PR TITLE
Virtual Study Group

### PR DESCRIPTION
**Pull request by taneeshaa15**
Hi @Sulagna-Dutta-Roy ,
I hope you're doing well. I've addressed the issue #2233 and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Requesting you again not to delete the existing instructions for the PR template above @taneeshaa15

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check and edit this

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Check this please!

**Comment by Sulagna-Dutta-Roy** [comment]
What? @taneeshaa15

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check the other PRs and edit the above template. 
@taneeshaa15

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Its same like other PR only and also in my changed files I cannot see any deleted file regarding PR Instructions.
Ma'am may you please redirect me to that file?

**Comment by Sulagna-Dutta-Roy** [comment]
Check this one #2281

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy Added README.md file

**Comment by Sulagna-Dutta-Roy** [comment]
Unfortunately readme file is not same as PR instructions. @taneeshaa15

**Comment by Sulagna-Dutta-Roy** [comment]
I hope you'll understand this now. Thanks @taneeshaa15 
Taneeshaaaa

**Comment by taneeshaa15** [comment]
@Sulagna-Dutta-Roy yes ma'am, doing the changes now

**Pull request closed without merging**
