### PR TITLE
Added talking_tom game

### PR DESCRIPTION
**Pull request by arunimaChintu**
# Description

Adds game "Talking Tom"

Fixes:  #1940 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
@arunimaChintu didn't know that the tech stack is Python instead of JavaScript. As per the code complexities I am Reducing to level 1

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Talking Tom Game/your files

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy sorry I was unaware it had to be Javascript, I will edit the code with Javascript... Please assign it to level3

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy I have updated the tech stack to Javascript. Please assign it to level 3

**Comment by Sulagna-Dutta-Roy** [comment]
Only 200+ points will be allocated because your two PRs contains total 90 points if you switch to javascript. @arunimaChintu

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy Updated to Talking Tom Game/ my files... and the tech stack is also updated to javascript... And, could you please explain the above said thing again, I could not get it.

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy Please merge this

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Where did you add the js files? @arunimaChintu

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
I don't think it's a proper JS files with no index,styling and manifest files. @arunimaChintu 
Only the JS files will be level1. Not level3 because it's not the proper project.
Kindly check the other projects structure.

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy I am getting this error while pushing the code: 
Screenshot 2024-06-30 at 9 40 05 PM

**Comment by arunimaChintu** [comment]
@Sulagna-Dutta-Roy Please help me push my code... I have added all the index,styling and manifest files accordingly...I just need to push it

**Comment by Sulagna-Dutta-Roy** [comment]
I don't have any access restrictions to this repo. And receiving multiple PRs from another PR. 
Do one thing I am closing this PR. you can push the changes again @arunimaChintu

**Comment by arunimaChintu** [comment]
okay Thanks @Sulagna-Dutta-Roy

**Pull request closed without merging**
