### PR TITLE
Added Email Validator App

### PR DESCRIPTION
**Pull request by SadafKausar2025**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #290 

#290 

## Added new Feature to the Project

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (1757)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Can you please check again? Because I can see Bill Spitter folders also. 
Check your branch

**Comment by SadafKausar2025** [comment]
Hi @Sulagna-Dutta-Roy 
 I removed that folder , I think now it's good to go

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add script files. Currently not showing as an extension

**Review by SyedImtiyaz-1 — APPROVED** [review]
All Set !

**Comment by SyedImtiyaz-1** [comment]
image


I think all the files are added, it's working.

**Comment by SadafKausar2025** [comment]
> Kindly add script files. Currently not showing as an extension

script file is already added

**Comment by SadafKausar2025** [comment]
Can you please merge this PR?

**Comment by Sulagna-Dutta-Roy** [comment]
> All Set !

Hey who are you? How did you approve the changes ?

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
