### PR TITLE
Added Forest Extension And Mercury Reader Extension

### PR DESCRIPTION
**Pull request by Dark-S8uL**
# Description
Forest Extension :
Implemented the Forest extension, which allows users to plant virtual trees to stay focused while browsing the internet. Users can set the growth time for each tree and watch it mature as they maintain focus on their tasks. This change fixes issue #1292.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
Added New Extension : Forest Extension #1292 

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resources
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Forest Extension (In Chrome) :
Screenshot 2024-06-09 105554

##

# Description
Mercury Reader Extension:
Implemented the Mercury Reader extension, which simplifies web pages for easier reading by removing ads, distractions, and formatting, leaving just the main content. This change addresses the issue of distractions and clutter on web pages, providing users with a streamlined reading experience. This change fix issue #1291 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
Added New Extension: Mercury Reader Extension #1291 

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resources
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Mercury Reader Extension (In Chrome) :
Screenshot 2024-06-09 113017

### CODE REVIEW

**Comment by Dark-S8uL** [comment]
@Sulagna-Dutta-Roy Please Assign it as Level3 as I have added two extensions in a single pull request.
I have Added Extensions #1291 and #1292.

**Comment by Sulagna-Dutta-Roy** [comment]
@Dark-S8uL Do you think it's the guidelines as per the gssoc? Because I know contributors need to make separate pull requests in a single issue. (1issue-1pull request rule) 
So why should I make this to level3?

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly create a branch before raising a pull request. I mentioned in the readme because master to master branch is not a healthy practice for all @Dark-S8uL

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
I can see two pull request here. Kindly check

**Comment by Dark-S8uL** [comment]
@Sulagna-Dutta-Roy I am creating a new branch and committing soon.

**Pull request closed without merging**
