### PR TITLE
added website bandwidth extension

### PR DESCRIPTION
**Pull request by samarsajad**
# Description

A simple extension that tells you your website bandwidth

Fixes:  #1174 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Sulagna-Dutta-Roy

**Comment by samarsajad** [comment]
@Sulagna-Dutta-Roy Ma'am I couldn't find the new contributing guidelines. If you could please share them so that i could get a better understanding , that would be very helpful. It was nice working with you and I loved contributing in this repo and would like to continue doing the same, if you are okay with it.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please remove the submodules folder

**Comment by samarsajad** [comment]
Made the changes and sent the new pull request #1406 Please review it

**Pull request closed without merging**
