### PR TITLE
determinant calculator

### PR DESCRIPTION
**Pull request by bhumika-1127**
@Sulagna-Dutta-Roy I have added a determinant calculator wrt issue number #578.
Kindly review and accept the PR.

image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Delete the.vscode files
Kindly add script files as it's not showing as an extension.

**Comment by bhumika-1127** [comment]
@Sulagna-Dutta-Roy I have made the changes. Kindly re-review.

**Comment by Sulagna-Dutta-Roy** [comment]
Still the .vscode file showing here. Can you please check

**Comment by bhumika-1127** [comment]
@Sulagna-Dutta-Roy can you share any ss that what is the problem, because from my side its ok and working in my browser.

image

image

**Comment by bhumika-1127** [comment]
@Sulagna-Dutta-Roy Please check it; if the issue still persists, let me know.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Checking

**Pull request merged**
