### PR TITLE
Concentraion game

### PR DESCRIPTION
**Pull request by mahek0620**
# Description

Find and match pairs of cards from memory.

Fixes:  #1800 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
memory-screenshot-3
memory-screenshot-2
memory-screenshot-1

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Last feedback was same about this directory name. 
It should be Concentration Game/your files. @mahek0620

**Comment by mahek0620** [comment]
@Sulagna-Dutta-Roy Since it took time and more efforts for creating the feature request for updating the labels if you are satisfied with the work

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly change the directory name: Concentration Game/your files 
@mahek0620 
Let me know how many points you've received from my repo?

**Comment by mahek0620** [comment]
2 PR of level2 was merged i.e 50 points

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by mahek0620** [comment]
> Kindly change the directory name: Concentration Game/your files @mahek0620 Let me know how many points you've received from my repo?

50 points

**Pull request merged**
