### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by P-lavanya16**
# Description

I have added a line for adding files before commiting to the repository 

- [x] This change requires a documentation update

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add your details in the pull request template.

**Comment by P-lavanya16** [comment]
What details to be add in pull request

**Comment by Sulagna-Dutta-Roy** [comment]
It seems you've removed the template. Please check this #105

**Comment by Sulagna-Dutta-Roy** [comment]
Please check this one: #105

**Comment by Sulagna-Dutta-Roy** [comment]
Closing this PR as another is raised.

**Pull request closed without merging**
