### PR TITLE
Reminder Pro -- Never forget a task with chrom

### PR DESCRIPTION
**Pull request by wilsonprodige**
Issue no: #25
Creating a new google chrome extension(Reminder Pro)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I setup the manifest file for this google chrome extension
- [x] I have setup the main extension popup and its css(styling) 
- [x] I have setup the background (service_worker) and the contentScript
- [x] I setup the add reminder functionality
- [x] I have setup the update reminder(updates the alarm/notification set )
- [x] I have setup the delete reminder functionality(deletes the reminder/notif specified
Screen Shot 2024-05-26 at 20 39 14
Screen Shot 2024-05-26 at 20 40 16

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

SETUP STEPS

-activate developer mode on chrome
-Load the unpacked code (Rémunération pro on your browser)
-enable chrome notifications and badges on your os
-open reminder pro extension, add a reminder and it shall show a
notification at that specific time

### CODE REVIEW

**Comment by sarthak-stranger** [comment]
@wilsonprodige Why This is not working on Browser?

**Comment by wilsonprodige** [comment]
Hi
For it to work
-activate developer mode on chrome
-Load the unpacked code (Rémunération pro on your browser)
-enable chrome notifications and badges on your os
-open reminder pro extension, add a reminder and it shall show a
notification at that specific time

Please in case you need a visual explanation I can make a loom showing all
that

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add all the details in the pull request template ⬆

**Comment by wilsonprodige** [comment]
Ok I will do so

**Comment by wilsonprodige** [comment]
i have just updated the pr (comment -- SETUP STEPS) @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Fill out the checklists and raise an issue first.

**Comment by wilsonprodige** [comment]
Ok

**Comment by wilsonprodige** [comment]
Hey @Sulagna-Dutta-Roy I have checked all the features of reminder pro(check list)
As for the issues I had already raised an issue for this

**Comment by wilsonprodige** [comment]
#505 issue

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Issue no was: #25 
Closing the new created issue

**Pull request merged**
