### PR TITLE
Added Fitness Extension

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Description

I've Added a fitness Extension

Fixes:  #832 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
I can see heavy dependencies here. Please delete all of these files including .vscode also. 
Only code files are enough to contribute in the open source programs. 113 files here with 18k+ pushes not a healthy practice

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am doing

**Comment by Sulagna-Dutta-Roy** [comment]
All the checks are failed here. Can't merge it because of project dependencies

**Comment by Ayushmaanagarwal1211** [comment]
ok i am fixing it

**Comment by Sulagna-Dutta-Roy** [comment]
No update since past few weeks. Closing this

**Pull request closed without merging**
