### PR TITLE
Added Buuny is lost game

### PR DESCRIPTION
**Pull request by DiwareNamrata23**
# Description

Added bunny is lost game

Fixes:  #2128 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
WhatsApp Image 2024-07-11 at 8 05 34 PM (1)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name as: Bunny Lost /your files

**Comment by Sulagna-Dutta-Roy** [comment]
Hey @DiwareNamrata23 

Kindly check your scores Immediately. As per the new Instructions contributors should not get 150 points from here. Close all your Issues @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
the points are not 150 from here they are less than it @Sulagna-Dutta-Roy can plz merge this pr

**Comment by Sulagna-Dutta-Roy** [comment]
This is pending since last week: Change the directory name as: Bunny Lost /your files @DiwareNamrata23

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly update @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
Screenshot 2024-07-25 at 10 31 21 PM
the total points are80

**Comment by Sulagna-Dutta-Roy** [comment]
> Screenshot 2024-07-25 at 10 31 21 PM the total points are80

KIndly check the directory name and change it

**Comment by DiwareNamrata23** [comment]
Sure maam

**Comment by DiwareNamrata23** [comment]
added changes to directory

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
