### PR TITLE
Tiny fishing game extension added

### LINKED ISSUE #1520: Add Tiny fishing game extension
**Is your feature request related to a problem? Please describe.**
I want to add a game extension,  it is called tiny fishing game.

**Describe the solution you'd like**
It is a very fun game . It is copy of classic fishing game with beautiful backgrounds , music and smooth experience

**Describe alternatives you've considered**
functionalities 🎮
1. You can use the arrow keys or mouse for moving the fishing rod.
2. By collecting the fishes you can score.
3. You can upgrade your attributes by using the money.
 
How to play? 🕹️
1. Use arrow keys to move the fishing rod !
2. Use the mouse to move the fish rod.

tiny-fishing

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
# Description

I have added a game extension called Tiny fishing it is made by html, css and mostly javascript.

Fixes #1520 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
tiny-fishing

### CODE REVIEW

**Comment by Pujan-sarkar** [comment]
@Sulagna-Dutta-Roy please change the label to level 2 or level 3 something, it is not a beginner level project  please check

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Tiny Fishing/your files

**Comment by Pujan-sarkar** [comment]
@Sulagna-Dutta-Roy  Is it will be very problem , i can't do it

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Tiny Fishing Game/your files

**Comment by Sulagna-Dutta-Roy** [comment]
Then I'm closing this Pull request. You can work on thin later.
And It's not a big problem, everyone is doing the same

**Comment by Pujan-sarkar** [comment]
@Sulagna-Dutta-Roy okay then I will send a new pr

**Comment by Sulagna-Dutta-Roy** [comment]
Sure. Closing this

**Pull request closed without merging**
