### PR TITLE
added the hit the numbers game extension

### PR DESCRIPTION
**Pull request by samarsajad**
# Description

Hit the numbers is a simple game  made in retro style where the user is prompted to hit the number displayed to win points.

Fixes:  #1504 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Sulagna-Dutta-Roy

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Hit The Numbers Game/your files

**Comment by samarsajad** [comment]
I made the changes . Kindly review my pull request @Sulagna-Dutta-Roy

**Comment by samarsajad** [comment]
Can you please review my pull request @Sulagna-Dutta-Roy . I made the changes

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
