### PR TITLE
added pocket extension

### PR DESCRIPTION
**Pull request by Aksshay88**
# Description

I have included the Pocket extension 

Fixes:  #1246 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Requesting you to check project readme. Because every project should have manifest.json files. I see that not added here 
And change the directory name as: Pocket Extension/your files

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy sure will check and change it

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy I have changes the suggestion you have asked for .I request you to review the pr.
Thanks in advance

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name as: Pocket Extension/your files

**Comment by Aksshay88** [comment]
@Sulagna-Dutta-Roy changed the file name as suggested .You could check the pr here

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
