### PR TITLE
Skii Game

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#2526

Fixes:  #2526 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please review the PR.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Anjaliavv51** [comment]
@Sulagna-Dutta-Roy please add level label

**Pull request merged**
