### PR TITLE
Added ColorPicker

### PR DESCRIPTION
**Pull request by ankit071105**
# Description
I have created a Color Fusion feature that allows users to choose a color and generate all possible color codes, including HSL, RGB, HEX, and more. Additionally, I have included a linear gradient theme where users can select two colors to generate a linear gradient. Users can customize the gradient direction (top, bottom, top-left, etc.) and adjust the percentage of each color.

This feature enhances the user experience by providing a comprehensive tool for color selection and gradient creation.

Fixes: #2534 

# Type of change
 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 This change requires a documentation update
# Checklist
 I have made this from my own
 I have taken help from some online resources
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have made corresponding changes to the documentation
 My changes generate no new warnings
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-07-29 at 10 12 55 AM
Screenshot 2024-07-29 at 10 12 50 AM

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
It seems my repository has already this project. Also why did you added this PR without opening the Issue? @ankit071105 
Kindly respond

**Comment by ankit071105** [comment]
You have assigned me this issue kindly check #2534

**Comment by Sulagna-Dutta-Roy** [comment]
> You have assigned me this issue kindly check #2534 

Then kindly add the Issue number in the above. It seems missing.
Change the directory name: Gradients Picker/your files @ankit071105

**Comment by ankit071105** [comment]
Ok

**Comment by ankit071105** [comment]
Changed  the file and added the issue number @Sulagna-Dutta-Roy  accept the Pull request

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
