### PR TITLE
Added falling words game

### PR DESCRIPTION
**Pull request by somilyadav7**
# Description
Added falling Words Game

Fixes:  #2154 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
how
home
game
game1
game_over

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: Falling Words/your files @pallasivasai

**Comment by somilyadav7** [comment]
> Change the directory name: Falling Words/your files @somilyadav7

Done

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add manifest files @somilyadav7

**Comment by somilyadav7** [comment]
> Kindly add manifest files @somilyadav7

Done

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
