### PR TITLE
Fixes issue #1668

### PR DESCRIPTION
**Pull request by Ajita369**
# Description
I added Git Search App.
Fixes:  #1668

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Change the directory name: GIF Search App/your files
And where is manifest file? @Ajita369

**Comment by Ajita369** [comment]
Can I create another pull request with the changes?

**Comment by Ajita369** [comment]
@Sulagna-Dutta-Roy sorry for the trouble, I created another pull request #1712 with required changes.

**Comment by Ajita369** [comment]
@Sulagna-Dutta-Roy sorry for the trouble, I created another pull request https://github.com/Sulagna-Dutta-Roy/GGExtensions/pull/1712 with required changes.

**Pull request closed without merging**
