### PR TITLE
power bi extension

### PR DESCRIPTION
**Pull request by NAVJOT-786**
# Description

This update introduces a new Chrome extension designed to help users quickly navigate to Power BI. The extension features a welcoming page with a typewriter effect and a button that directs users to the Power BI question functionality page.

Fixes:  #1193 

## Type of change

- [ X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2024-06-08 at 12 38 11 AM

### CODE REVIEW

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy added new extension please check

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Manifest.json file is empty

**Comment by NAVJOT-786** [comment]
@Sulagna-Dutta-Roy done added manifest.json please check

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Reduced the level after seeing the code. It seems like an simple extension entry level

**Comment by Sulagna-Dutta-Roy** [comment]
Deleted this PR because of cloning issue.

**Pull request merged**
