### PR TITLE
added random paragraph generator

### PR DESCRIPTION
**Pull request by partha120804**
# Description

Nowte typing speed check give you a 430 character long paragraph made up of random words

Fixes:  #2327 

## Type of change

feature enchancement

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Only 150 points you'll get as per the new Instructions I received @partha120804 
It's my responsibility to update new contributors

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add manifest files @partha120804

**Comment by partha120804** [comment]
> Only 150 points you'll get as per the new Instructions I received @partha120804 It's my responsibility to update new contributors

Yeah I know, and also technical changes like this are not counted in those 150, right ?

**Comment by partha120804** [comment]
the manifest was already present and did not require much changes i updated the version number, and added some details

**Comment by partha120804** [comment]
@Sulagna-Dutta-Roy please review this PR

**Comment by Sulagna-Dutta-Roy** [comment]
> > Only 150 points you'll get as per the new Instructions I received @partha120804 It's my responsibility to update new contributors
> 
> Yeah I know, and also technical changes like this are not counted in those 150, right ?

My any kind of contribution will counted for the labels but it should be limited to 150 only. No more points after this

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by partha120804** [comment]
> > > Only 150 points you'll get as per the new Instructions I received @partha120804 It's my responsibility to update new contributors
> > 
> > 
> > Yeah I know, and also technical changes like this are not counted in those 150, right ?
> 
> Any kind of contribution will counted for the labels but it should be limited to 150 only. No more points after this @partha120804

ohh, ok will keep that in mind

**Pull request merged**
