### PR TITLE
script.js (song tracker) improvement in code in efficiency

### PR DESCRIPTION
**Pull request by vyanky1227**
**ISSUE NUMBER : script.js (song tracker) improvement in code in efficiency #166 **

Avoiding Duplicate Fetch Calls:

Handling Errors and Loading States:

Consolidating HTML Element Creation:

Adding Play/Pause Toggle:

Volume Control:

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #166

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
SCREENSHOTS:
Screenshot 2024-05-15 150008

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add the Issue name in the pull request template.

**Comment by vyanky1227** [comment]
@Sulagna-Dutta-Roy ma'am I have edited the above pull request template by adding issue number #167

**Comment by vyanky1227** [comment]
Ma'am please merge this request. Thank you for guiding me.

**Comment by vyanky1227** [comment]
> Please add the Issue name in the pull request template.

added issue #166

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
